services:

  postgres:
    image: postgres:16
    container_name: recruitment-postgres
    environment:
      POSTGRES_DB: recruitment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ayoub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: recruitment-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recruitment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ayoub
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: recruitment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    external: true
    name: stage_postgres_data